
import { Badge, LeaderboardEntry, Region, SupperClub, UserProfile } from './types';

export const sampleSupperClubs: SupperClub[] = [
  {
    id: '1',
    name: 'The Supper Club',
    description: 'A classic Wisconsin supper club featuring prime rib, fish fry, and old fashioneds.',
    location: { lat: 44.5133, lng: -89.5745 },
    address: '123 Main St',
    city: 'Wausau',
    state: 'Wisconsin',
    county: 'Marathon',
    image: '/lovable-uploads/48b7e577-f054-41cb-bb60-30bf86cd9c01.png',
    rating: 4.7,
    reviews: [
      {
        id: 'r1',
        userId: 'u1',
        userName: 'Jennifer Smith',
        userAvatar: 'https://randomuser.me/api/portraits/women/62.jpg',
        rating: 5,
        comment: 'Authentic supper club experience with amazing prime rib!',
        date: '2023-09-15',
        foodRating: 5,
        serviceRating: 4,
        ambienceRating: 5,
      }
    ],
    visited: true,
    specialties: ['Prime Rib', 'Fish Fry', 'Old Fashioned'],
    openHours: 'Tue-Sun: 4PM-10PM',
    phoneNumber: '(715) 555-1234',
    website: 'https://thesupperclub.com',
  },
  {
    id: '2',
    name: 'Northwoods Dining',
    description: 'Rustic dining experience with a focus on local ingredients and traditional recipes.',
    location: { lat: 45.1789, lng: -89.6532 },
    address: '456 Forest Ave',
    city: 'Minocqua',
    state: 'Wisconsin',
    county: 'Oneida',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cmVzdGF1cmFudHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60',
    rating: 4.5,
    reviews: [],
    visited: false,
    specialties: ['Walleye', 'Venison', 'Craft Beer'],
    openHours: 'Wed-Sun: 5PM-9PM',
    phoneNumber: '(715) 555-5678',
  },
  {
    id: '3',
    name: 'Lakeside Supper',
    description: 'Waterfront dining with stunning sunset views and fresh seafood.',
    location: { lat: 43.0775, lng: -89.4008 },
    address: '789 Lake Drive',
    city: 'Madison',
    state: 'Wisconsin',
    county: 'Dane',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cmVzdGF1cmFudCUyMGludGVyaW9yfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60',
    rating: 4.8,
    reviews: [],
    visited: false,
    specialties: ['Perch', 'Steak', 'Cocktails'],
    openHours: 'Tue-Sun: 4:30PM-10PM',
    phoneNumber: '(608) 555-9012',
    website: 'https://lakesidesupper.com',
  },
  {
    id: '4',
    name: 'Dutch Mill',
    description: 'Family-owned since 1967, known for generous portions and homemade desserts.',
    location: { lat: 42.7015, lng: -87.9335 },
    address: '321 County Road G',
    city: 'Kenosha',
    state: 'Wisconsin',
    county: 'Kenosha',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8cmVzdGF1cmFudHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60',
    rating: 4.3,
    reviews: [],
    visited: true,
    specialties: ['Broasted Chicken', 'Potato Pancakes', 'Cherry Pie'],
    openHours: 'Mon-Sun: 7AM-9PM',
    phoneNumber: '(262) 555-3456',
  },
  {
    id: '5',
    name: 'The Pines Resort',
    description: 'Elegant dining with northwoods charm and an extensive wine list.',
    location: { lat: 46.0512, lng: -89.3896 },
    address: '567 Highway 51',
    city: 'Mercer',
    state: 'Wisconsin',
    county: 'Iron',
    image: 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHJlc3RhdXJhbnR8ZW58MHx8MHx8fDA%3D%3D&auto=format&fit=crop&w=500&q=60',
    rating: 4.9,
    reviews: [],
    visited: false,
    specialties: ['Lobster', 'Prime Rib', 'Wine Selection'],
    openHours: 'Thu-Mon: 5PM-10PM',
    phoneNumber: '(715) 555-7890',
    website: 'https://pinesresort.com',
  },
];

export const badges: Badge[] = [
  {
    id: 'b1',
    name: 'Supper Club Newbie',
    description: 'You\'ve visited your first supper club!',
    image: 'https://img.icons8.com/color/96/000000/prize.png',
    level: 'new',
    requiredVisits: 1,
  },
  {
    id: 'b2',
    name: 'Experienced Foodie',
    description: 'You\'ve visited 5 supper clubs!',
    image: 'https://img.icons8.com/color/96/000000/medal2.png',
    level: 'experienced',
    requiredVisits: 5,
  },
  {
    id: 'b3',
    name: 'Midwest Master',
    description: 'You\'ve visited all the supper clubs in a region!',
    image: 'https://img.icons8.com/color/96/000000/trophy.png',
    level: 'master',
    requiredVisits: 10,
  },
];

export const currentUser: UserProfile = {
  id: 'u1',
  name: 'Jennifer Smith',
  avatar: 'https://randomuser.me/api/portraits/women/62.jpg',
  clubsVisited: ['1', '4'],
  badges: [badges[0]],
  totalVisits: 2,
  rank: 3,
  joinDate: '2023-08-01',
  bio: 'Food enthusiast exploring the Midwest one supper club at a time.'
};

export const leaderboard: LeaderboardEntry[] = [
  {
    id: 'u2',
    name: 'Michael Johnson',
    avatar: 'https://randomuser.me/api/portraits/men/32.jpg',
    totalVisits: 8,
    rank: 1,
  },
  {
    id: 'u3',
    name: 'Sarah Williams',
    avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
    totalVisits: 6,
    rank: 2,
  },
  {
    id: currentUser.id,
    name: currentUser.name,
    avatar: currentUser.avatar,
    totalVisits: currentUser.totalVisits,
    rank: currentUser.rank,
  },
  {
    id: 'u4',
    name: 'Robert Brown',
    avatar: 'https://randomuser.me/api/portraits/men/22.jpg',
    totalVisits: 1,
    rank: 4,
  },
  {
    id: 'u5',
    name: 'Jessica Davis',
    avatar: 'https://randomuser.me/api/portraits/women/17.jpg',
    totalVisits: 1,
    rank: 5,
  },
];

export const regions: Region[] = [
  {
    id: 'r1',
    name: 'North Woods',
    states: ['Wisconsin'],
  },
  {
    id: 'r2',
    name: 'Great Lakes',
    states: ['Wisconsin', 'Michigan', 'Minnesota'],
  },
  {
    id: 'r3',
    name: 'Driftless Area',
    states: ['Wisconsin', 'Iowa', 'Minnesota', 'Illinois'],
  },
];

export const cuisineTypes = [
  'Prime Rib',
  'Fish Fry',
  'Broasted Chicken',
  'Seafood',
  'Steaks',
  'German',
  'Italian',
  'Traditional',
  'Farm-to-Table',
];
